name: Parkalert
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.2.1
  latlong2: ^0.9.0
  shared_preferences: ^2.0.15
  flutter_blue_classic: ^0.0.6
  app_settings: ^6.1.1
  geofencing_api: ^2.0.0
  fl_location: ^5.0.0
  flutter_activity_recognition: ^4.0.0

  android_intent_plus: ^5.3.1
  permission_handler: ^12.0.1
  url_launcher: ^6.2.6
  flutter_dotenv: ^5.1.0
  geolocator: ^14.0.2
  google_maps_flutter: ^2.12.3
  flutter_compass: ^0.8.1
  geocoding: ^4.0.0
  audioplayers: ^6.5.0

  # file_picker: ^6.1.1
  #utilities Packages
  http: ^1.4.0
  uuid: ^4.5.1
  intl: ^0.20.2
  logger: ^2.6.0
  #icons
  iconsax_flutter: ^1.0.1

  #flutter splash screen
  flutter_native_splash: ^2.4.6

  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.1

  #state management
  get: ^4.7.2
  get_storage: ^2.1.1
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^19.3.1
  workmanager: ^0.9.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_native_splash:
  color: "#0A0E61"
  image: "assets/logos/logopartalert.png"
  branding: "assets/logos/brandingforparkalert.png"
  android_12:
    color: "#0A0E61"
    image: "assets/logos/logopartalert.png"
    branding: "assets/logos/brandingforparkalert.png"
    web: false
    android: true
    ios: true
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logos/iconlogo.png"
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/on_boarding_images/
    - assets/icons/
    - assets/logos/
    - .env
    - assets/sounds/tone1.wav
    - assets/sounds/tone2.wav
    - assets/sounds/tone3.wav
    - assets/sounds/tone4.wav
    - assets/sounds/tone5.wav
    - assets/sounds/tone6.wav

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito/Nunito-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Nunito/Nunito-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Nunito/Nunito-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito/Nunito-Black.ttf
          weight: 900
