name: Parkalert
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.2.1
  latlong2: ^0.9.0
  flutter_dotenv: ^5.1.0
  geolocator: ^11.0.0
  google_maps_flutter: ^2.12.3
  geocoding: ^2.0.5
  #utilities Packages
  http: ^1.4.0
  uuid: ^4.5.1
  intl: ^0.20.2
  logger: ^2.6.0
  url_launcher: ^6.3.1
  #icons
  iconsax_flutter: ^1.0.1

  #flutter splash screen
  flutter_native_splash: ^2.4.6

  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.1

  #state management
  get: ^4.7.2
  get_storage: ^2.1.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logos/iconlogo.png"
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/on_boarding_images/
    - assets/icons/
    - assets/logos/
    - .env

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito/Nunito-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Nunito/Nunito-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Nunito/Nunito-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito/Nunito-Black.ttf
          weight: 900
